OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyDZDDvhc5-iRdv_vNdM9_1fAmvKDVBoRVY"
SERPER_API_KEY="673e7b9ba21c606af2d261fd44a5d269057a0a5a"
